!
! feldstein_neves1984.f90
!
! Vector field function for: feldstein_neves1984
! These functions are to be used with DDE_SOLVER_M.
!
! This file was generated by the program VFGEN, version: 2.6.0.dev2
! Generated on  9-Feb-2022 at 11:08
!
!
! The lags are: {-beta+t}

MODULE DEFINE_feldstein_neves1984_DDEs

    IMPLICIT NONE
    INTEGER, PARAMETER :: NEQN=1, NLAGS=1

CONTAINS

    SUBROUTINE feldstein_neves1984_ddes(t,x_,Zlags_,vf_)
    ! Arguments
    DOUBLE PRECISION :: t
    DOUBLE PRECISION, DIMENSION(:) :: x_, vf_
    DOUBLE PRECISION, DIMENSION(:,:) :: Zlags_
    INTENT(IN) :: t, x_, Zlags_
    INTENT(OUT) :: vf_
    ! Local variables
    DOUBLE PRECISION beta, delayedy
    DOUBLE PRECISION y
    ! State variables
    y          = x_(1)
    ! Expressions
    beta = -2.0**((1.0/2.0))+y

    delayedy = Zlags_(1,1)

    ! The vector field
    vf_(1) = (1.0/2.0)*( t+1.0)**(-(1.0/2.0))*delayedy


    RETURN
    END SUBROUTINE feldstein_neves1984_ddes

    SUBROUTINE feldstein_neves1984_history(t,x_)
    DOUBLE PRECISION :: t
    DOUBLE PRECISION, DIMENSION(:) :: x_
    INTENT(IN) :: t
    INTENT(OUT) :: x_

    x_(1) = 1.0


    RETURN
    END SUBROUTINE feldstein_neves1984_history

    SUBROUTINE feldstein_neves1984_beta(t,x_,bval_)
    ! Arguments
    DOUBLE PRECISION :: t
    DOUBLE PRECISION, DIMENSION(:) :: x_
    DOUBLE PRECISION, DIMENSION(:) :: bval_
    INTENT(IN) :: t, x_
    INTENT(OUT) :: bval_
    ! Local variables
    DOUBLE PRECISION beta, delayedy
    DOUBLE PRECISION y

    ! State variables
    y          = x_(1)
    ! Expressions
    beta = -2.0**((1.0/2.0))+y

    bval_(1) = beta

    END SUBROUTINE feldstein_neves1984_beta

END MODULE DEFINE_feldstein_neves1984_DDEs
