!
! paul1992.f90
!
! Vector field function for: paul1992
! These functions are to be used with DDE_SOLVER_M.
!
! This file was generated by the program VFGEN, version: 2.6.0.dev2
! Generated on  8-Feb-2022 at 21:50
!
!
! The lags are: { t-beta}

MODULE DEFINE_paul1992_DDEs

    IMPLICIT NONE
    INTEGER, PARAMETER :: NEQN=1, NLAGS=1

CONTAINS

    SUBROUTINE paul1992_ddes(t,x_,Zlags_,vf_)
    ! Arguments
    DOUBLE PRECISION :: t
    DOUBLE PRECISION, DIMENSION(:) :: x_, vf_
    DOUBLE PRECISION, DIMENSION(:,:) :: Zlags_
    INTENT(IN) :: t, x_, Zlags_
    INTENT(OUT) :: vf_
    ! Local variables
    DOUBLE PRECISION beta, delayedy
    DOUBLE PRECISION y
    ! State variables
    y          = x_(1)
    ! Expressions
    beta =  log(y)-1.0

    delayedy = Zlags_(1,1)

    ! The vector field
    vf_(1) = y/( t+1.0)*delayedy


    RETURN
    END SUBROUTINE paul1992_ddes

    SUBROUTINE paul1992_history(t,x_)
    DOUBLE PRECISION :: t
    DOUBLE PRECISION, DIMENSION(:) :: x_
    INTENT(IN) :: t
    INTENT(OUT) :: x_

    x_(1) = 1.0


    RETURN
    END SUBROUTINE paul1992_history

    SUBROUTINE paul1992_beta(t,x_,bval_)
    ! Arguments
    DOUBLE PRECISION :: t
    DOUBLE PRECISION, DIMENSION(:) :: x_
    DOUBLE PRECISION, DIMENSION(:) :: bval_
    INTENT(IN) :: t, x_
    INTENT(OUT) :: bval_
    ! Local variables
    DOUBLE PRECISION beta, delayedy
    DOUBLE PRECISION y

    ! State variables
    y          = x_(1)
    ! Expressions
    beta =  log(y)-1.0

    bval_(1) = beta

    END SUBROUTINE paul1992_beta

END MODULE DEFINE_paul1992_DDEs
