!
! delay_oscillator.f90
!
! Vector field function for: delay_oscillator
! These functions are to be used with DDE_SOLVER_M.
!
! This file was generated by the program VFGEN, version: 2.6.0.dev2
! Generated on  8-Feb-2022 at 16:36
!
!
! The lags are: {tau}

MODULE DEFINE_delay_oscillator_DDEs

    IMPLICIT NONE
    INTEGER, PARAMETER :: NEQN=1, NLAGS=1
    ! Parameters
    DOUBLE PRECISION tau

CONTAINS

    SUBROUTINE delay_oscillator_ddes(t,x_,Zlags_,vf_)
    ! Arguments
    DOUBLE PRECISION :: t
    DOUBLE PRECISION, DIMENSION(:) :: x_, vf_
    DOUBLE PRECISION, DIMENSION(:,:) :: Zlags_
    INTENT(IN) :: t, x_, Zlags_
    INTENT(OUT) :: vf_
    ! Local variables
    DOUBLE PRECISION delayedx
    DOUBLE PRECISION x
    DOUBLE PRECISION Pi
    Pi = 3.1415926535897932385D0
    ! State variables
    x          = x_(1)
    ! Expressions
    delayedx = Zlags_(1,1)

    ! The vector field
    vf_(1) = -delayedx


    RETURN
    END SUBROUTINE delay_oscillator_ddes

    SUBROUTINE delay_oscillator_history(t,x_)
    DOUBLE PRECISION :: t
    DOUBLE PRECISION, DIMENSION(:) :: x_
    INTENT(IN) :: t
    INTENT(OUT) :: x_

    x_(1) = sin(t)


    RETURN
    END SUBROUTINE delay_oscillator_history

END MODULE DEFINE_delay_oscillator_DDEs
