name: Test dde_solver_m

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: delay oscillator
      run: |
        cd tests/delay_oscillator
        bash run_delay_oscillator_test.sh
    - name: Paul (1992)
      run: |
        cd tests/paul1992
        bash run_paul1992_test.sh
