name: Test dde_solver_m

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test with simple oscillator
      run: |
        cd tests
        bash run_delay_oscillator_test.sh
